package rules.forward;

import com.weatherforecast.model.MeasuredHourlyWeatherData;
import com.weatherforecast.model.PredictedHourlyTemperature;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;


rule "create predicted temperature object if it does not exist for date and time"
salience 6
    when
        not(
            PredictedHourlyTemperature(
                date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).toLocalDate(),
                hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour()
            )
        )
    then
        insert(new PredictedHourlyTemperature(LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1)));
        System.out.println("Object created");
end

rule "calculate average temperature for this hour in the past three days"
salience 5
    when
        $m1: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(1).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            $t1: temperature
        )
        $m2: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(2).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            $t2: temperature
        )
        $m3: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(3).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            $t3: temperature
        )
        $p: PredictedHourlyTemperature(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            temperature == null
        )
        $average: Double() from (( $t1 * 1.6 + $t2 + $t3 * 0.4 ) / 3)
    then
        System.out.println("Base predicted temperature: " + $average);
        modify($p){
            setTemperature($average)
        }
end

rule "lower predicted temperature based on precipitation"
salience 4
    when
        $p: PredictedHourlyTemperature(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            temperature != null,
            precipitationApplied == false
        )
        $m1: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(1).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            precipitation > 1.0
        )
        $m2: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(2).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            precipitation == 0.0
        )
    then
        modify($p){
            applyPrecipitationFactor(0.9),
            setPrecipitationApplied(true)
        }
        System.out.println("Temperature after precipitation: " + $p.getTemperature());
end

rule "update precipitation applied flag"
salience 3
    when
        $p: PredictedHourlyTemperature(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            temperature != null,
            precipitationApplied == false
        )
    then
        modify($p) {
            setPrecipitationApplied(true)
        }
        System.out.println("Temperature not modified by precipitation.");
end

rule "detect rising temperature trend"
salience 2
no-loop true
    when
        $p: PredictedHourlyTemperature(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            temperature != null,
            precipitationApplied == true
        )
        $m1: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(1).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            $t1: temperature
        )
        $m2: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(2).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            $t2: temperature < $t1
        )
        $m3: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(3).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            $t3: temperature < $t2
        )
        $trendModifier: Double() from ((( ($t1 - $t2) * 1.5 + ($t2 - $t3) * 0.5 ) / 2) * 1.5)
    then
        modify($p) {
            addTemperature($trendModifier)
        }
        System.out.println("Temperature after trend: " + $p.getTemperature());
end

rule "detect falling temperature trend"
salience 1
no-loop true
    when
        $p: PredictedHourlyTemperature(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            temperature != null,
            precipitationApplied == true
        )
        $m1: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(1).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            $t1: temperature
        )
        $m2: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(2).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            $t2: temperature > $t1
        )
        $m3: MeasuredHourlyWeatherData(
            date == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).minusDays(3).toLocalDate(),
            hour == LocalDateTime.parse("2023-05-29T20:13:24.089848700").plusHours(1).getHour(),
            $t3: temperature > $t2
        )
        $trendModifier: Double() from ((( ($t1 - $t2) * 1.5 + ($t2 - $t3) * 0.5 ) / 2) * 1.5)
    then
        modify($p) {
            addTemperature($trendModifier)
        }
        System.out.println("Temperature after trend: " + $p.getTemperature());
end